name: Fetch Repository

on:
    schedule:
      - cron: '*/5 * * * *' #every 5 mins

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Fetch Repository
      run: |
            git fetch --all
            git pull
